queue: normalsr
ncpus: 208
jobfs: 10GB
mem: 1000GB

walltime: 00:20:00
jobname: test_wombatlite

model: access-om3

exe: access-om3-MOM6
input:
    - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-datm-ESMFmesh.nc
    - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-drof-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite_2/hgrid.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite_2/vcoord.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite/bathymetry_mod.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite_2/init_tracers_modified.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite_2/obgc_obc.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite_2/init_eta.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite_2/init_vel.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite_2/grid_spec.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite_2/ocean_mosaic.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite_2/access-rom3-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite_2/access-rom3-nomask-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite/dust_DS.nc  
#    - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0

#    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/hgrid.nc
#    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/vcoord.nc
    #- /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/bathymetry.nc
#    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/init_tracers_modified.nc
    #- /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/obgc_obc.nc
#    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/init_eta.nc
#    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/init_vel.nc
#    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/grid_spec.nc
#    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/ocean_mosaic.nc
#    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/access-rom3-ESMFmesh.nc
#    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/access-rom3-nomask-ESMFmesh.nc
#    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_bgc/dust_DS.nc
    - /g/data/qv56/replicas/input4MIPs/CMIP6Plus/OMIP/MRI/MRI-JRA55-do-1-6-0/
 
modules:
    use:
        - /g/data/vk83/prerelease/modules
    load:
        - access-om3/pr144-1
        - nco/5.0.5
        - model-tools/mppnccombine-fast
        
collate:
  restart: true
  mpi: true
  walltime: 3:00:00
  mem: 30GB
  ncpus: 4
  queue: expresssr
  exe: mppnccombine-fast
  
runlog: false
metadata: 
    enable: false

platform:
    nodesize: 104
    nodemem: 512

#userscripts:
    #archive: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/archive.sh




payu_minimum_version: 1.1.6
