# PBS configuration

# If submitting to a different project to your default, uncomment line below 
# and change project code as appropriate; also set shortpath below
# project: x77

# Force payu to always find, and save, files in this scratch project directory
# (you may need to add the corresponding PBS -l storage flag in sync_data.sh)
# shortpath: /scratch/v45

queue: normalsr
ncpus: 208
jobfs: 10GB
mem: 1000GB

walltime: 00:20:00
jobname: test_wombatlite

model: access-om3

exe: access-om3-MOM6
input:
    - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-datm-ESMFmesh.nc
    - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-drof-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs//NW_shelf_iaf_notides_wombatlite/hgrid.nc
    - /scratch/nm03/ee8016/regional_mom6_configs//NW_shelf_iaf_notides_wombatlite/vcoord.nc
    - /scratch/nm03/ee8016/regional_mom6_configs//NW_shelf_iaf_notides_wombatlite/bathymetry.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite/init_tracers_modified.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite/obgc_obc.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite/init_eta.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite/init_vel.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite/grid_spec.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite/ocean_mosaic.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite/access-rom3-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite/access-rom3-nomask-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NW_shelf_iaf_notides_wombatlite/dust_DS.nc  
    - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0
 
collate: false
runlog: false
metadata: 
    enable: false

platform:
    nodesize: 104
    nodemem: 512

#userscripts:
    #archive: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/archive.sh

modules:
    use:
        - /g/data/vk83/modules
    load:

        - access-om3/2025.08.001


payu_minimum_version: 1.1.6
